DROP TABLE Author;
DROP TABLE Blog;
DROP TABLE Comment;
DROP TABLE Tag;
DROP TABLE Post;
DROP TABLE Post_Tag;

CREATE TABLE Author (
id INTEGER NOT NULL,
username VARCHAR(255) NULL,
password VARCHAR(255) NULL,
email VARCHAR(255) NULL,
bio VARCHAR(255) NULL,
favourite_section VARCHAR(255) NULL,
PRIMARY KEY (id)
);

CREATE TABLE Blog (
id INTEGER NOT NULL,
author_id INTEGER NULL,
title VARCHAR(255) NULL,
PRIMARY KEY (id)
);

CREATE TABLE Comment (
id INTEGER NOT NULL,
post_id INTEGER NULL,
name VARCHAR(255) NULL,
comment VARCHAR(255) NULL,
PRIMARY KEY (id)
);

CREATE TABLE Tag (
id INTEGER NOT NULL,
name VARCHAR(255) NULL,
PRIMARY KEY (id)
);

CREATE TABLE Post (
id INTEGER NOT NULL,
blog_id INTEGER NULL,
author_id INTEGER NULL,
created_on VARCHAR(255) NULL,
section VARCHAR(255) NULL,
subject VARCHAR(255) NULL,
draft INTEGER NULL,
body VARCHAR(255) NULL,
PRIMARY KEY (id)
);

CREATE TABLE Post_Tag (
post_id INTEGER NOT NULL,
tag_id INTEGER NULL,
PRIMARY KEY (post_id)
);

